const RESOURCES = require('./RESOURSES');

const EXCHANGE_STRATEGY = {
    [RESOURCES.OBSD]: RESOURCES.NOVO,
    [RESOURCES.NOVOE]: RESOURCES.OBSD,
    [RESOURCES.NOVOM]: RESOURCES.OBSD,
    [RESOURCES.NOVOF]: RESOURCES.OBSD,
};

module.exports = EXCHANGE_STRATEGY;