import RESOURCES from './RESOURSES';

const EXCHANGE_STRATEGY = {
    [RESOURCES.OBSD]: RESOURCES.NOVO,
    [RESOURCES.NOVOE]: RESOURCES.OBSD,
    [RESOURCES.NOVOM]: RESOURCES.OBSD,
    [RESOURCES.NOVOF]: RESOURCES.OBSD,
};

export default EXCHANGE_STRATEGY;