import RESOURCES from './RESOURSES';

const MIN_TRANSACTION_VALUE = {
    [RESOURCES.NOVOE]: 65,
    [RESOURCES.NOVOM]: 60,
    [RESOURCES.NOVOF]: 55,
    [RESOURCES.OBSD]: 1,
    [RESOURCES.NOVO]: 3,
};

export default MIN_TRANSACTION_VALUE;