const API_ENDPOINTS = {
    ASSETS: 'ASSETS',
    ACCOUNTS: 'ACCOUNTS',
    SALES: 'SALES',
    TEMPLATES: 'TEMPLATES',
    TEMPLATES_STATS: 'TEMPLATES_STATS',
    LOGS: 'LOGS',
    TRANSFERS: 'TRANSFERS',
};

export default API_ENDPOINTS;
